/*
 * parameters.h
 *
 *  Created on: 15.03.2020
 *      Author: Adrian
 */
#ifndef PARAMETERS_H_
#define PARAMETERS_H_

#include "settings.h"

extern const setting_t *parametersTable[];
extern const uint16_t paramsTableLen;

//change every time if you change parameters table
#define PARAMETERS_VERSION 3

#define PARAMETERS_MAX_NAME_LENGTH 25

/******************** PRINTER ********************/

#define PARAMETER_PRINT_STEPPER_FACTOR 5.729578f //Wczeœniej by³o 5.84f
#define PARAMETER_PRINT_STEPPER_FACTOR_MIN 1
#define PARAMETER_PRINT_STEPPER_FACTOR_MAX 1000

#define PARAMETER_PRINT_START_POS 3500
#define PARAMETER_PRINT_START_POS_MIN 0
#define PARAMETER_PRINT_START_POS_MAX 2000000000

#define PARAMETER_PRINT_EJECT_TRIGGER_POS 240000
#define PARAMETER_PRINT_EJECT_TRIGGER_POS_MIN 0
#define PARAMETER_PRINT_EJECT_TRIGGER_POS_MAX 2000000000

#define PARAMETER_PRINT_EJECT_POS 50000
#define PARAMETER_PRINT_EJECT_POS_MIN 0
#define PARAMETER_PRINT_EJECT_POS_MAX 2000000000

#define PARAMETER_PRINT_TIMEOUT_Z 10000
#define PARAMETER_PRINT_TIMEOUT_Z_MIN 1000
#define PARAMETER_PRINT_TIMEOUT_Z_MAX 60000

#define PARAMETER_PRINT_TIMEOUT_Y 10000
#define PARAMETER_PRINT_TIMEOUT_Y_MIN 1000
#define PARAMETER_PRINT_TIMEOUT_Y_MAX 60000

#define PARAMETER_PRINT_PE_LOWER_LIMIT 9680
#define PARAMETER_PRINT_PE_LOWER_LIMIT_MIN 0
#define PARAMETER_PRINT_PE_LOWER_LIMIT_MAX 2000000000

#define PARAMETER_PRINT_PE_UPPER_LIMIT 240000//1050
#define PARAMETER_PRINT_PE_UPPER_LIMIT_MIN 0
#define PARAMETER_PRINT_PE_UPPER_LIMIT_MAX 2000000000

/******************** Y MOTOR ********************/
#define PARAMETER_HOME_SPEED_Y	1000
#define PARAMETER_HOME_SPEED_Y_MIN 1
#define PARAMETER_HOME_SPEED_Y_MAX 20000

#define PARAMETER_HOME_ACCEL_Y	10000
#define PARAMETER_HOME_DECEL_Y	10000

/* Parameters for motor during printing */
#define PARAMETER_PRINT_SPEED_Y 2000
#define PARAMETER_PRINT_SPEED_Y_MIN 1
#define PARAMETER_PRINT_SPEED_Y_MAX 20000

#define PARAMETER_PRINT_ACCEL_Y 75000
#define PARAMETER_PRINT_ACCEL_Y_MIN 1
#define PARAMETER_PRINT_ACCEL_Y_MAX 200000

#define PARAMETER_PRINT_DECEL_Y 75000
#define PARAMETER_PRINT_DECEL_Y_MIN 1
#define PARAMETER_PRINT_DECEL_Y_MAX 200000

/* Parameters for motor during movement*/
#define PARAMETER_MOVE_SPEED_Y 2000
#define PARAMETER_MOVE_SPEED_Y_MIN 1
#define PARAMETER_MOVE_SPEED_Y_MAX 20000

#define PARAMETER_MOVE_ACCEL_Y 10000
#define PARAMETER_MOVE_ACCEL_Y_MIN 1
#define PARAMETER_MOVE_ACCEL_Y_MAX 200000

#define PARAMETER_MOVE_DECEL_Y 10000
#define PARAMETER_MOVE_DECEL_Y_MIN 1
#define PARAMETER_MOVE_DECEL_Y_MAX 200000

/* Parameters for motor during jog */
#define PARAMETER_JOG_SPEED_Y 1000
#define PARAMETER_JOG_SPEED_Y_MIN 1
#define PARAMETER_JOG_SPEED_Y_MAX 20000

#define PARAMETER_JOG_ACCEL_Y 10000
#define PARAMETER_JOG_ACCEL_Y_MIN 1
#define PARAMETER_JOG_ACCEL_Y_MAX 200000

#define PARAMETER_JOG_DECEL_Y 10000
#define PARAMETER_JOG_DECEL_Y_MIN 1
#define PARAMETER_JOG_DECEL_Y_MAX 200000

/******************** Z MOTOR ********************/

#define PARAMETER_HOME_SPEED_Z	1000
#define PARAMETER_HOME_SPEED_Z_MIN 1
#define PARAMETER_HOME_SPEED_Z_MAX 20000

#define PARAMETER_HOME_ACCEL_Z	10000
#define PARAMETER_HOME_DECEL_Z	10000

/* Parameters for motor during printing */
#define PARAMETER_PRINT_SPEED_Z 2000
#define PARAMETER_PRINT_SPEED_Z_MIN 1
#define PARAMETER_PRINT_SPEED_Z_MAX 20000

#define PARAMETER_PRINT_ACCEL_Z 1000000
#define PARAMETER_PRINT_ACCEL_Z_MIN 1
#define PARAMETER_PRINT_ACCEL_Z_MAX 2000000

#define PARAMETER_PRINT_DECEL_Z 1000000
#define PARAMETER_PRINT_DECEL_Z_MIN 1
#define PARAMETER_PRINT_DECEL_Z_MAX 2000000

/* Parameters for motor during movement*/
#define PARAMETER_MOVE_SPEED_Z 2000
#define PARAMETER_MOVE_SPEED_Z_MIN 1
#define PARAMETER_MOVE_SPEED_Z_MAX 20000

#define PARAMETER_MOVE_ACCEL_Z 10000
#define PARAMETER_MOVE_ACCEL_Z_MIN 1
#define PARAMETER_MOVE_ACCEL_Z_MAX 200000

#define PARAMETER_MOVE_DECEL_Z 10000
#define PARAMETER_MOVE_DECEL_Z_MIN 1
#define PARAMETER_MOVE_DECEL_Z_MAX 200000

/* Parameters for motor during jog */
#define PARAMETER_JOG_SPEED_Z 1000
#define PARAMETER_JOG_SPEED_Z_MIN 1
#define PARAMETER_JOG_SPEED_Z_MAX 20000

#define PARAMETER_JOG_ACCEL_Z 10000
#define PARAMETER_JOG_ACCEL_Z_MIN 1
#define PARAMETER_JOG_ACCEL_Z_MAX 200000

#define PARAMETER_JOG_DECEL_Z 10000
#define PARAMETER_JOG_DECEL_Z_MIN 1
#define PARAMETER_JOG_DECEL_Z_MAX 200000

#endif /* PARAMETERS_H_ */
